### ISSUE TITLE
Embed original gist comments?

### ISSUE THREAD

**Issue by eyecatchup** [nicegist/nicegist.github.io#10]
This issue is to track discussion whether to render the comments on the original gist or not.

You can see the current implementation here: https://nicegist.github.io/84aec347c6a1b90890dad8953d7e8c67#gist-comments

The comment section is only shown for gists that have received comments. (Compare the link above to [this Nicegist without comments](https://nicegist.github.io/2f35faad4d4fa55810422283f7bc3b78))

What I like about it is, that you can easily link to comments (since I create unique anchor links for each comment). See: https://nicegist.github.io/84aec347c6a1b90890dad8953d7e8c67#comment-1876170

Let me know what you think. I'm still not sure if I should keep it or if its too distracting (because, ultimately, the idea of Nicegist is to offer a clean representation for gists).

**Comment by fuzzy76** [comment]
Hmm... I'm torn. But that sort of also means I don't have a strong opinion either way. :) But design-wise I think they look nice.

**Comment by eyecatchup** [comment]
Closing, since it's not an open issue. Further discussion welcome. Pinned this issue.
