### ISSUE TITLE
Favicon?

### ISSUE THREAD

**Issue by fuzzy76** [nicegist/nicegist.github.io#3]
I wish for a favicon, something that let me recognize bookmarks and tabs pointing to nicegist. You probably want to add meta tags for iOS/Android specific larger icons and perhaps even a [webapp manifest](https://developer.mozilla.org/en-US/docs/Web/Manifest).

**Comment by eyecatchup** [comment]
Hey @fuzzy76, I've added a favicon and touch icons. I don't see the benefit of a manifest file here. Why should anyone pin the Nicegist site to his homescreen?

**Comment by fuzzy76** [comment]
Not the site, but perhaps a single gist. :) The manifest file is also a handy way for telling various browsers how to treat/render bookmarks and shortcuts to gists on nicegist.

**Comment by eyecatchup** [comment]
@fuzzy76 Since it doesn't harm ;), I've added a manifest file too.
