### ISSUE TITLE
Support GFM tasklists

### ISSUE THREAD

**Issue by fuzzy76** [nicegist/nicegist.github.io#37]
Since Github Flavored Markup [support task lists](https://github.github.com/gfm/#task-list-items-extension-) I was hoping you'd consider adding [markdown-it-task-lists](https://github.com/revin/markdown-it-task-lists). I'd prefer enabled checkboxes so I could use Nicegist for checklists.

**Comment by eyecatchup** [comment]
Hi @fuzzy76, sorry for coming back that late. I missed the notification.

The thing with enabled checkboxes is, that I'd have to add much more logic to the Nicegist site. 

On Gist, every time you check/uncheck a checkbox, it will automatically create a commit to reflect your changes. I could easily add GFM task list support with enabled checkboxes. But the state would not be persisted on page reload. And that woulnd't be helpful at all, right? On the other hand, I don't want to create a fully-fledged integration, where your checkbox changes would trigger a commit.

I'm leaving it open to give me some more time to think about.

**Comment by fuzzy76** [comment]
Actually for my specific use (checklists that I use again and again), that would be perfect. I realise other people might not, but I see nicegist as a read-only presentation layer and not an editing frontend.

**Comment by fuzzy76** [comment]
I would actually rephrase it: I would specifically *not* want nicegist to save my changes. I want to create checklists that come up unchecked every time I load the page, ready to be reused as many times as I want.

That would be very helpful. :)

**Comment by eyecatchup** [comment]
@fuzzy76 (Read-only) Task list support added. See example here: https://nicegist.github.io/1b3041b19870ff91730e550fa5cd129c
