### ISSUE TITLE
Doesn't support HTML inside markdown?

### ISSUE THREAD

**Issue by fuzzy76** [nicegist/nicegist.github.io#42]
HTML inside Markdown is a pretty substantial tool, but nicegist seem to escape all HTML.

[Demonstration of problem](https://nicegist.github.io/1ed0a0a328ba35a56bbb4da271e75892)
vs
[How Github renders it](https://gist.github.com/fuzzy76/1ed0a0a328ba35a56bbb4da271e75892)

**Comment by fuzzy76** [comment]
That would be the html-flag in markdown-it... https://markdown-it.github.io/markdown-it/#MarkdownIt.new

**Comment by eyecatchup** [comment]
Closed by #44
