### ISSUE TITLE
Checkboxes doesn't indent like other lists

### ISSUE THREAD

**Issue by fuzzy76** [nicegist/nicegist.github.io#43]
Checkboxes are lists, and github/gist treats them like one. But nicegist doesn't.

[Gist example](https://gist.github.com/fuzzy76/270833491d9b0e964cc1d6585ed3b034)

[Nicegist render](https://nicegist.github.io/270833491d9b0e964cc1d6585ed3b034)

**Comment by eyecatchup** [comment]
Indentation for task lists fixed by #46
